# Generated by Django 5.2.2 on 2025-06-13 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото профиля')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный профиль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
